
crime_group_mapping = {
    624: 'Assault / Battery',
    626: 'Assault / Battery',
    860: 'Assault / Battery',
    625: 'Assault / Battery',
    623: 'Assault / Battery',
    627: 'Assault / Battery',
    622: 'Assault / Battery',
    437: 'Misc. Infrequent Offenses:',
    230: 'Life-Threatening Violent Crime',
    236: 'Life-Threatening Violent Crime',
    121: 'Life-Threatening Violent Crime',
    110: 'Life-Threatening Violent Crime',
    251: 'Life-Threatening Violent Crime',
    235: 'Life-Threatening Violent Crime',
    122: 'Life-Threatening Violent Crime',
    231: 'Life-Threatening Violent Crime',
    250: 'Life-Threatening Violent Crime',
    330: 'Burglary / Theft (From Vehicle)',
    310: 'Burglary / Theft',
    440: 'Burglary / Theft',
    420: 'Burglary / Theft',
    341: 'Burglary / Theft',
    350: 'Burglary / Theft',
    320: 'Burglary / Theft',
    441: 'Burglary / Theft',
    450: 'Burglary / Theft',
    351: 'Burglary / Theft',
    451: 'Burglary / Theft',
    470: 'Burglary / Theft',
    331: 'Burglary / Theft (From Vehicle)',
    421: 'Burglary / Theft (From Vehicle)',
    210: 'Robbery (Violent Theft)',
    220: 'Robbery (Violent Theft)',
    510: 'Vehicle/Bike/Boat Stolen',
    480: 'Vehicle/Bike/Boat Stolen',
    520: 'Vehicle/Bike/Boat Stolen',
    487: 'Vehicle/Bike/Boat Stolen',
    485: 'Vehicle/Bike/Boat Stolen',
    740: 'Property Damage / Threats',
    745: 'Property Damage / Threats',
    930: 'Property Damage / Threats',
    888: 'Property Damage / Threats',
    761: 'Property Damage / Threats',
    648: 'Property Damage / Threats',
    763: 'Property Damage / Threats',
    442: 'Shoplifting/Pickpocket',
    343: 'Shoplifting/Pickpocket',
    443: 'Shoplifting/Pickpocket',
    352: 'Shoplifting/Pickpocket',
    753: 'Misc. Infrequent Offenses',
    886: 'Misc. Infrequent Offenses',
    940: 'Misc. Infrequent Offenses',
    850: 'Misc. Infrequent Offenses',
    812: 'Misc. Infrequent Offenses',
    815: 'Misc. Infrequent Offenses',
    910: 'Misc. Infrequent Offenses',
    647: 'Misc. Infrequent Offenses',
    820: 'Misc. Infrequent Offenses',
    932: 'Misc. Infrequent Offenses',
    755: 'Misc. Infrequent Offenses',
    920: 'Misc. Infrequent Offenses',
    760: 'Misc. Infrequent Offenses',
    822: 'Misc. Infrequent Offenses',
    813: 'Misc. Infrequent Offenses',
    933: 'Misc. Infrequent Offenses',
    668: 'Misc. Infrequent Offenses',
    943: 'Misc. Infrequent Offenses',
    438: 'Misc. Infrequent Offenses',
    806: 'Misc. Infrequent Offenses',
    922: 'Misc. Infrequent Offenses',
    805: 'Misc. Infrequent Offenses',
    434: 'Misc. Infrequent Offenses'
}



safety_rel_crimes = {
    624: 'BATTERY - SIMPLE ASSAULT',
    740: 'VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)',
    626: 'INTIMATE PARTNER - SIMPLE ASSAULT',
    330: 'BURGLARY FROM VEHICLE',
    510: 'VEHICLE - STOLEN',
    310: 'BURGLARY',
    440: 'THEFT PLAIN - PETTY ($950 & UNDER)',
    230: 'ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT',
    210: 'ROBBERY',
    420: 'THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)',
    745: 'VANDALISM - MISDEAMEANOR ($399 OR UNDER)',
    930: 'CRIMINAL THREATS - NO WEAPON DISPLAYED',
    341: 'THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIVESTK,PROD',
    888: 'TRESPASSING',
    236: 'INTIMATE PARTNER - AGGRAVATED ASSAULT',
    331: 'THEFT FROM MOTOR VEHICLE - GRAND ($400 AND OVER)',
    761: 'BRANDISH WEAPON',
    480: 'BIKE - STOLEN',
    350: 'THEFT, PERSON',
    442: 'SHOPLIFTING - PETTY THEFT ($950 & UNDER)',
    343: 'SHOPLIFTING-GRAND THEFT ($950.01 & OVER)',
    443: 'SHOPLIFTING - ATTEMPT',
    320: 'BURGLARY, ATTEMPTED',
    220: 'ATTEMPTED ROBBERY',
    860: 'BATTERY WITH SEXUAL CONTACT',
    625: 'OTHER ASSAULT',
    623: 'BATTERY POLICE (SIMPLE)',
    121: 'RAPE, FORCIBLE',
    627: 'CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT',
    753: 'DISCHARGE FIREARMS/SHOTS FIRED',
    886: 'DISTURBING THE PEACE ',
    648: 'ARSON',
    437: 'RESISTING ARREST',
    940: 'EXTORTION',
    520: 'VEHICLE - ATTEMPT STOLEN',
    850: 'INDECENT EXPOSURE',
    812: 'CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 YRS OLDER)',
    352: 'PICKPOCKET',
    251: 'SHOTS FIRED AT INHABITED DWELLING',
    110: 'CRIMINAL HOMICIDE',
    421: 'THEFT FROM MOTOR VEHICLE - ATTEMPT',
    815: 'SEXUAL PENETRATION W/FOREIGN OBJECT',
    910: 'KIDNAPPING',
    441: 'THEFT PLAIN - ATTEMPT',
    647: 'THROWING OBJECT AT MOVING VEHICLE',
    820: 'ORAL COPULATION',
    932: 'PEEPING TOM',
    763: 'STALKING',
    235: 'CHILD ABUSE (PHYSICAL) - AGGRAVATED ASSAULT',
    122: 'RAPE, ATTEMPTED',
    351: 'PURSE SNATCHING',
    231: 'ASSAULT WITH DEADLY WEAPON ON POLICE OFFICER',
    450: 'THEFT FROM PERSON - ATTEMPT',
    250: 'SHOTS FIRED AT MOVING VEHICLE, TRAIN OR AIRCRAFT',
    755: 'BOMB SCARE',
    920: 'KIDNAPPING - GRAND ATTEMPT',
    760: 'LEWD/LASCIVIOUS ACTS WITH CHILD',
    822: 'HUMAN TRAFFICKING - COMMERCIAL SEX ACTS',
    813: 'CHILD ANNOYING (17YRS & UNDER)',
    933: 'PROWLER',
    668: 'EMBEZZLEMENT, GRAND THEFT ($950.01 & OVER)',
    434: 'FALSE IMPRISONMENT',
    943: 'CRUELTY TO ANIMALS',
    438: 'RECKLESS DRIVING',
    806: 'PANDERING',
    487: 'BOAT - STOLEN',
    622: 'BATTERY ON A FIREFIGHTER',
    451: 'PURSE SNATCHING - ATTEMPT',
    922: 'CHILD STEALING',
    805: 'PIMPING',
    485: 'BIKE - ATTEMPTED STOLEN',
    470: 'TILL TAP - GRAND THEFT ($950.01 & OVER)',
}