# Generated by Django 2.1.7 on 2019-03-24 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyAnalysisRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('estimate', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('pred_type', models.CharField(choices=[('PC', 'estimated_time_proximity_incidents')], max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('publish_timestamp', models.DateTimeField()),
                ('current', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='safetyanalysisrequest',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safety.SafetyModel'),
        ),
    ]
