# Generated by Django 2.1.7 on 2019-04-02 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0002_auto_20190401_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetyanalysis',
            name='estimate',
        ),
        migrations.RemoveField(
            model_name='safetyanalysis',
            name='model',
        ),
    ]
