# Generated by Django 2.1.7 on 2019-04-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0003_auto_20190402_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyanalysis',
            name='tf',
            field=models.CharField(choices=[('RT', 'Real-Time'), ('D', 'Daily')], default='RT', max_length=2),
        ),
    ]
