# Generated by Django 2.1.7 on 2019-04-14 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0004_safetyanalysis_tf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetyanalysis',
            name='tf',
        ),
    ]
