# Generated by Django 2.1.7 on 2019-05-12 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crimeincident',
            old_name='_id',
            new_name='row_id',
        ),
    ]
