# Generated by Django 2.1.7 on 2019-05-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0003_auto_20190513_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimeincident',
            name='date_occ',
            field=models.CharField(max_length=70),
        ),
    ]
