# Generated by Django 2.1.7 on 2019-05-13 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0005_dailycrimevolume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crimeincident',
            old_name='date_occ',
            new_name='date_occ_str',
        ),
        migrations.RenameField(
            model_name='dailycrimevolume',
            old_name='date_occ',
            new_name='date_occ_str',
        ),
    ]
