# Generated by Django 2.1.7 on 2019-05-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0007_crimespremisesvolume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crimeincident',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='crimeincident',
            old_name='longitude',
            new_name='lon',
        ),
    ]
