# Generated by Django 2.1.7 on 2019-05-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrymeClassifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('file_path', models.TextField()),
                ('target', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=False)),
                ('risk_rating_low', models.FloatField()),
                ('risk_rating_medium', models.FloatField()),
                ('risk_rating_high', models.FloatField()),
                ('risk_rating_very_high', models.FloatField()),
            ],
        ),
    ]
