# Generated by Django 2.1.7 on 2019-05-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crymeclassifier',
            name='crime_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
