# Generated by Django 2.1.7 on 2019-08-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0002_crymeclassifier_crime_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('log_loss_n_ab', models.FloatField()),
                ('log_loss_n_b', models.FloatField()),
                ('log_loss_n_t', models.FloatField()),
                ('log_loss_n_btv', models.FloatField()),
                ('log_loss_n_vbbs', models.FloatField()),
                ('log_loss_n_pdt', models.FloatField()),
                ('log_loss_n_ltvc', models.FloatField()),
                ('log_loss_n_sp', models.FloatField()),
                ('log_loss_n_mio', models.FloatField()),
                ('log_loss_n_nr', models.FloatField()),
            ],
        ),
    ]
