# Generated by Django 2.1.7 on 2019-08-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifiers', '0004_auto_20190825_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelperformance',
            name='day',
            field=models.TextField(),
        ),
    ]
