# Generated by Django 2.1.7 on 2019-03-24 02:16

from django.db import migrations, models
import json
import os

from regions.models import GeometricRegion


geometry_files = [{
    'path': os.path.abspath(os.getcwd() + '/regions/migrations/fixtures/city_of_los_angeles_geometry.json'),
    'name': 'city of los angeles',
}]


def ingest_regions(apps, schema_editor):
    for geometry_file in geometry_files:
        with open(geometry_file['path'], 'r') as geom_file:
            polygon_coords = str(json.loads(geom_file.read())['geometries'][0]['coordinates'][0][0])
        GeometricRegion.objects.create(name=geometry_file['name'], polygon_coordinates=polygon_coords)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeometricRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('polygon_coordinates', models.TextField()),
            ],
        ),
        migrations.RunPython(ingest_regions),
    ]
